title: "Here with Yu.Y"
email: "892016730@qq.com"
description: "热烈因何孤僻，闭塞所以自由。"
baseurl: ""
url: "https://chen-yy20.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  # 移除这行，因为 jekyll-imagemagick 不是标准插件
  # - jekyll-imagemagick

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Collections
collections:
  photo_albums:
    output: true
    permalink: /photography/:name/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - .gitignore

# Google Analytics
google_analytics: G-4H97N6X3TM

# 图片相关设置
image_path: "assets/images"

# 默认配置
defaults:
  - scope:
      path: ""
      type: "photo_albums"
    values:
      layout: "album"
  # 为文章添加默认布局
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"