title: "Here with Yu.Y"
email: "892016730@qq.com"
description: "热烈因何孤僻，闭塞所以自由。"
baseurl: ""
url: "https://chen-yy20.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - .gitignore

# Google Analytics
google_analytics: G-4H97N6X3TM  # 替换为你的测量ID